services:
  - type: web
    name: poe-discord-bot
    env: go
    region: oregon
    plan: free
    buildCommand: go build -o bot
    startCommand: ./bot
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
